syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.android.emulator.control";
option objc_class_prefix = "AEC";

package android.emulation.control;
import "google/protobuf/empty.proto";

// Legacy WebRTC contract exposed by Google Emulator Container 30.1.2.
service Rtc {
  rpc requestRtcStream(google.protobuf.Empty) returns (RtcId) {}
  rpc sendJsepMessage(JsepMsg) returns (google.protobuf.Empty) {}
  rpc receiveJsepMessages(RtcId) returns (stream JsepMsg) {}
  rpc receiveJsepMessage(RtcId) returns (JsepMsg) {}
}

message RtcId {
  string guid = 1;
}

message JsepMsg {
  RtcId id = 1;
  string message = 2;
}
